import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fun Flower Facts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Fun Flower Facts</h1>
        <nav>
          <Link className="nav" href="/">
            Home
          </Link>
          <Link className="nav" href="/posts">
            Posts
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
