import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fun Flower Facts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="h1">🌼 Fun Flower Facts 🌼</h1>
        <nav className="nav">
          <Link href="/">Home</Link>
          <Link href="/posts">Posts</Link>
          <Link href="/posts/new">New Post</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
